os:
    - osx
#    - linux
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          createuser -s postgres;
      else
          sudo /etc/init.d/postgresql stop;
          sudo /etc/init.d/postgresql start;
      fi
  - psql -c 'CREATE DATABASE vapordm;' -U postgres
  - psql -c "CREATE USER vapordm WITH PASSWORD 'vapordm';" -U postgres

before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build -c release
    - swift test

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"
    - bash <(curl -s https://codecov.io/bash)
